[build]
  base = ""

[build.processing]
  skip_processing = false

[[redirects]]
  from = "https://woominsbook.netlify.app/session"
  to = "https://woomin-facebook.herokuapp.com/session"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

