[build]
  base = "dist"

[build.processing]
  skip_processing = false

[[redirects]]
  from = "/session"
  to = "https://woomin-facebook.herokuapp.com/session"
  status = 200
  force = false
  headers = {X-From = "Netlify"}
