[build]
  base = "/"

[build.processing]
  skip_processing = false

[[redirects]]
  from = "/session"
  to = "https://woomin-facebook.herokuapp.com/session"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

frontend.com/api/session
